-- 코드를 입력하세요
SELECT
    CONCAT('/home/grep/src/', UGF.BOARD_ID, '/', UGF.FILE_ID, UGF.FILE_NAME, UGF.FILE_EXT) AS FILE_PATH
FROM (SELECT BOARD_ID
    , MAX(VIEWS) AS M
FROM USED_GOODS_BOARD
GROUP BY BOARD_ID
ORDER BY M DESC
LIMIT 1) TMP
    INNER JOIN USED_GOODS_FILE UGF
        ON TMP.BOARD_ID = UGF.BOARD_ID
ORDER BY FILE_ID DESC