-- 코드를 입력하세요
SELECT 
    UGS.USER_ID,
    UGS.NICKNAME,
    CONCAT(UGS.CITY,' ',UGS.STREET_ADDRESS1,' ',UGS.STREET_ADDRESS2) AS 전체주소,
    CONCAT(LEFT(UGS.TLNO,3),'-',SUBSTR(UGS.TLNO,4,4),'-',RIGHT(UGS.TLNO,4)) AS 전화번호
FROM 
    USED_GOODS_BOARD UGB
LEFT OUTER JOIN USED_GOODS_USER UGS
    ON UGS.USER_ID = UGB.WRITER_ID
GROUP BY UGB.WRITER_ID
HAVING COUNT(UGB.WRITER_ID) >= 3
ORDER BY UGB.WRITER_ID DESC

