# -- 코드를 입력하세요
# SELECT
#     PD.PRODUCT_CODE,
#     SUM(PD.PRICE * OS.SALES_AMOUNT) AS SALES
# FROM
#     PRODUCT PD
#     INNER JOIN OFFLINE_SALE OS
#         ON OS.PRODUCT_ID = PD.PRODUCT_ID 
# GROUP BY PRODUCT_CODE
# ORDER BY SALES DESC

SELECT 
    PD.PRODUCT_CODE, 
    SUM(SALES_AMOUNT * PD.PRICE) AS SALES
FROM PRODUCT PD 
    INNER JOIN OFFLINE_SALE OS 
        ON OS.PRODUCT_ID = PD.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE ASC