SELECT
    UGB.TITLE AS TITLE,
    UGB.BOARD_ID AS BOARD_ID,
    UGR.REPLY_ID AS REPLY_ID,
    UGR.WRITER_ID AS WRITER_ID,
    UGR.CONTENTS AS CONTENTS,
    DATE_FORMAT(UGR.CREATED_DATE,'%Y-%m-%d') AS CREATED_DATE
FROM
    USED_GOODS_BOARD UGB
    INNER JOIN USED_GOODS_REPLY UGR
        ON UGR.BOARD_ID = UGB.BOARD_ID
WHERE
    UGB.CREATED_DATE LIKE ('2022-10%')
    # SUBSTR(UGB.CREATED_DATE,1,7) = '2022-10'
    ORDER BY UGR.CREATED_DATE, UGB.TITLE