-- 코드를 입력하세요
SELECT
    DISTINCT CRH.CAR_ID
FROM
    CAR_RENTAL_COMPANY_CAR CRCC
    INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY CRH
    ON CRH.CAR_ID = CRCC.CAR_ID
WHERE 
    DATE_FORMAT(START_DATE,'%m') = 10 AND CRCC.CAR_TYPE = '세단'
ORDER BY CAR_ID DESC